### ISSUE TITLE
Impossible de lancer le logiciel

### ISSUE THREAD

**Issue by Antho7900** [iR3SH/MultiCompte2#1]
Bonjour,

J'ai télecharger votre  logiciel et lu le read me, puis ai téléchargé .NET Desktop Runtime 5.0.17 comme demandé, mais je n'arrive pas a lancer le logiciel, je ne trouve pas le fichier .exe, seulement un fichier icone.

Merci par avance pour votre réponse.

**Comment by iR3SH** [comment]
C'est sûrement dû à une exception de ton anti-virus

**Comment by Antho7900** [comment]
![image](https://user-images.githubusercontent.com/109134479/180123957-c40ddc01-5ce2-4525-ab06-8eec60e887b2.png)
-------------------------------------------------------------
-------------------------------------------------------------
![image](https://user-images.githubusercontent.com/109134479/180123999-fbd771d6-fd5c-48a8-97b8-16849ba01375.png)

Je ne pense pas regarde, je viens de désactiver l'Av puis retélécharger et extraire ton dossier mais nulle trace du fichier ".exe" pour lancer ton logiciel.

**Comment by iR3SH** [comment]
Tu as télécharger la version non compilé pour les développeurs c'est pour ça, il faut que tu télécharges la version Release
