### ISSUE TITLE
Un logiciel malveillant est détecté dans une dll

### ISSUE THREAD

**Issue by yvanb26** [iR3SH/MultiCompte2#3]
![Capture d’écran 2022-08-30 175843](https://user-images.githubusercontent.com/16401883/187484748-f135e341-06a4-4dee-949f-d2755ed602ac.png)

**Comment by Antho7900** [comment]
Salut mec, comment tu as fait sltp pour lancer le logiciel déjà  ? il n'y a pas de raccourci pour lancer le truc, tu as un lieu de téléchargement avec raccourci ?

**Comment by yvanb26** [comment]
> Salut mec, comment tu as fait sltp pour lancer le logiciel déjà ? il n'y a pas de raccourci pour lancer le truc, tu as un lieu de téléchargement avec raccourci ?

Tu télécharge le fichier rar dans Releases, tu décompresse avec winrar et là ta un dossier avec fichier .exe. Mais cela n'empêche qu'il y a quelque chose de malveillant dans la DLL

**Comment by iR3SH** [comment]
Il n’y a rien malveillant dedans c’est un faux positif, tu aurais au moins pu checker le code avant tout.

**Comment by yvanb26** [comment]
> Il n’y a rien malveillant dedans c’est un faux positif, tu aurais au moins pu checker le code avant tout.

Bah écoute, je suis Technicien en maintenance informatique de métier et non développeur, mon antivirus me dis qu'il y a une infection donc il bloque, à toi de développer quelque chose de sain, par ce que cela peut ressembler à une tentative de récupération de comptes et surtout pour tes utilisateurs c'est très peu rassurant. Un utilisateur n'est pas forcément développeur

**Comment by iR3SH** [comment]
Merci je suis au courant, le code initial n’est pas de moi je l’ai mentionné, il suffit d’utiliser le File.IO de C# pour qu’un antivirus sorte un faux positif donc ça n’a rien à voir et pas besoin d’être développeur pour comprendre plus de 50% d’un code il suffit de savoir parler anglais au minimum m’enfin bref je clos si t’es pas confiant le l’utilise pas et c’est réglé

**Comment by yvanb26** [comment]
> Merci je suis au courant, le code initial n’est pas de moi je l’ai mentionné, il suffit d’utiliser le File.IO de C# pour qu’un antivirus sorte un faux positif donc ça n’a rien à voir et pas besoin d’être développeur pour comprendre plus de 50% d’un code il suffit de savoir parler anglais au minimum m’enfin bref je clos si t’es pas confiant le l’utilise pas et c’est réglé

Ah bah jolie façon de répondre à ses utilisateurs, ça donne encore plus confiance en toi... Tu pourrais au moins le précisé sur le front que cela peut générer un faux positif, et le développement c'est pas forcément une question d'anglais, perso j'ai jamais mis le nez dans le dev par ce que cela ne m'intéresse absolument pas.

**Comment by iR3SH** [comment]
Je t’ai pas dit ça méchamment si jamais hein, je partage les gens en font ce qu’ils veulent du projet, je ne l’ai pas précisé parce que je n’en ai pas eu pour ma part c’est pour ça

**Comment by Antho7900** [comment]
Merci a vous pour ma part j'ai pu utiliser le logiciel et il marche a merveille, mon antivirus "kaspersky" même en effectuant une analyse ne le détecte pas comme virus.
IR3SH serait-il possible d'avoir un moyen de te contacter en privé comme discord par exemple je ne sais pas si c'est possible d'envoyer un mp via Github je suis novice dessus.

**Comment by yvanb26** [comment]
> Merci a vous pour ma part j'ai pu utiliser le logiciel et il marche a merveille, mon antivirus "kaspersky" même en effectuant une analyse ne le détecte pas comme virus. IR3SH serait-il possible d'avoir un moyen de te contacter en privé comme discord par exemple je ne sais pas si c'est possible d'envoyer un mp via Github je suis novice dessus.

Oui cela est normale par ce que c'est un "simple" antivirus, j'utilise un Antimalware, mais certes se petit logiciel reste quand même bien utile !

**Comment by Antho7900** [comment]
Enfaite j'aimerais contacter le dev parce qu'il y'a une autre version de ce logiciel de multi compte développé il y'a 3/4 ans par un serveur privé de dofus, cette version est bien plus ergonomique et propose d'avantage de fonctionnalités, le seul hic ? les dév qui l'ont fait pour le serveur privé de dofus a l'époque y ont mit une limitation qui fait que tu ne peux l'utiliser qu'en lançant dofus avec leur serveur a eux et pas dofus officiel.

iR3SH est-ce que cela t'intéresserait de bosser sur la nouvelle version bien plus performante pour juste lui enlever la limitation ? le serveur privé de dofus en question n'existe même plus rendant l'utilisation du soft juste impossible

![image](https://user-images.githubusercontent.com/109134479/188167084-7a647c96-b114-4f98-90ed-6b0dcc1f786d.png)
![image](https://user-images.githubusercontent.com/109134479/188167804-e3660402-5f4b-4e4b-9670-13b68a1d803f.png)

**Comment by yvanb26** [comment]
Ok, tu parle de ce dépôt là : https://github.com/Slyker/MultiTool ? Si tel est le cas, il n'a pas les sources...

**Comment by Antho7900** [comment]
> Ok, tu parles de ce dépôt là : https://github.com/Slyker/MultiTool ? Si tel est le cas, il n'a pas les sources...

Merci Yvan pour la rapidité de tes réponses, oui il s'agit de celui-là exactement ! je ne savais pas que le dev de l'époque avait partager en dehors du forum du serveur privé, donc le soucis c'est qu'il a partagé son logiciel prêt a l'emploie mais sans le code ? il n'y a pas un moyen de faire sans ? après tout je veux juste supprimer la limitation visible sur le deuxième screen
